spring:
  application:
    name: flux
  datasource:
    url: jdbc:postgresql://localhost:5432/flux
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    username: admin
    password: admin


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  port: 8080

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  region: eu-west-1
  bucket:
    name:
      cover: book-covers
      file: book-files


deepl:
  api:
    key: ${DEEPL_API_KEY}


langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GOOGLE_API_KEY}
      model-name: gemini-2.5-flash
#      log-requests-and-responses: true
    streaming-chat-model:
      api-key: ${GOOGLE_API_KEY}
      model-name: gemini-2.5-flash





